-
    description: parser log from kafka
    sql: >-
        CREATE TABLE RAW_DATA (
                             `message` Array<string>,
                             `rowtime` TIMESTAMP(3) METADATA FROM 'timestamp',
                             WATERMARK FOR `rowtime` AS `rowtime` - INTERVAL '1' SECOND
        ) WITH (
          'connector' = 'kafka',
          'topic' = 'test',
          'csv.array-element-delimiter' = '|',
          'properties.bootstrap.servers' = 'localhost:9092',
          'format' = 'csv'
        )
-
    description: change to game format
    sql: >-
        CREATE VIEW log as SELECT
        rowtime,
        proctime() as `proctime`,
        message[1] as `timestamps`,
        message[2] as `userId`,
        message[3] as `userName`,
        message[4] as `social`,
        message[5] as `partner`,
        message[6] as `refCode`,
        message[7] as `platformId`,
        message[8] as `source`,
        message[9] as `groupId`,
        message[10] as `actionId`,
        cast(message[11] as BIGINT) as `gold`,
        cast(message[12] as BIGINT) as `xu`,
        cast(message[13] as BIGINT) as `dGold`,
        cast(message[14] as BIGINT) as `dXu`,
        message[15] as `c15`,
        message[16] as `c16`,
        message[17] as `c17`,
        message[18] as `c18`,
        message[19] as `c19`,
        message[20] as `c20`,
        message[21] as `c21`,
        message[22] as `c22`,
        message[23] as `c23`,
        message[24] as `c24`,
        message[25] as `c25`,
        message[26] as `c26`,
        message[27] as `c27`,
        message[28] as `c28`,
        message[29] as `c29`,
        message[30] as `c30`
        FROM RAW_DATA

